# Generated by Django 5.1.3 on 2024-12-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesabank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
